"""creation table tache

Revision ID: f70accbebee4
Revises: 
Create Date: 2026-05-04 13:02:13.963167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f70accbebee4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('etat', sa.String(length=50), nullable=True),
    sa.Column('dateEch', sa.Date(), nullable=True),
    sa.Column('dateCre', sa.Date(), nullable=True),
    sa.Column('dateMaj', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tache_id'), 'tache', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tache_id'), table_name='tache')
    op.drop_table('tache')
    # ### end Alembic commands ###
